/**
 * Brands and teams — work section ticker. Edit order or strings anytime.
 */
export const clients = [
  "Independent Health",
  "Nickelback",
  "NYS Peace Officers",
  "Warner Bros Records",
  "cp-commerce.com",
  "Goo Goo Dolls",
  "Cute Is What We Aim For",
  "ChristmasCentral.com",
  "Pats Record Company",
  "Roc City Premiums",
  "Computer SOS",
  "U & S Services",
  "Alanis Morissette",
  "Stark Tech Group",
  "NyRA Trophy",
  "Clair Global",
  "David Cook",
  "Paul Hager",
  "Sosume Touring Inc",
  "Good Charamel Records Inc",
  "Seventeen",
  "Anderson Seeds and Garden",
  "Beth Orton",
  "Tanya Tucker",
  "Hilton Hotels",
  "Spyro Gyro",
  "Anuel AA",
  "Set It Off",
  "Leslie Mosier",
  "Mighty Mighty Bosstones",
  "Dave Melillo",
  "Phil Lesh",
  "Mike Malinin",
  "Korel Tunador",
  "Brad Fernquist",
  "Juno Awards",
  "John Rzeznik",
  "Bub Glass",
  "NCR",
  "M-POS Anywhere",
  "WeSueU, LLC",
] as const;
